name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: treeform/setup-nim-action@v2
    - uses: mymindstorm/setup-emsdk@v14

    - run: nimble install -y
    - run: nimble install boxy

    - run: nim c examples/basic.nim
    - run: nim c examples/basic_boxy.nim
    - run: nim c examples/basic_textured_quad.nim
    - run: nim c examples/basic_triangle.nim
    - run: nim c examples/callbacks.nim
    - run: nim c examples/clipboard.nim
    - run: nim c examples/cursor_position_test.nim
    - run: nim c examples/custom_cursor.nim
    - run: nim c examples/fixedsize.nim
    - run: nim c examples/fullscreen.nim
    - run: nim c examples/highdpi.nim
    # - run: nim c examples/httprequest.nim
    - run: nim c examples/icon.nim
    - run: nim c examples/opengl_version.nim
    - run: nim c examples/property_changes.nim
    - run: nim c examples/screens.nim
    - run: nim c examples/system_cursors.nim
    - run: nim c examples/tray.nim
    - run: nim c examples/websocket.nim

    - run: nim c -d:emscripten examples/basic.nim
    - run: nim c -d:emscripten examples/basic_boxy.nim
    - run: nim c -d:emscripten examples/basic_textured_quad.nim
    - run: nim c -d:emscripten examples/basic_triangle.nim
    - run: nim c -d:emscripten examples/callbacks.nim
    - run: nim c -d:emscripten examples/clipboard.nim
    - run: nim c -d:emscripten examples/cursor_position_test.nim
    - run: nim c -d:emscripten examples/custom_cursor.nim
    - run: nim c -d:emscripten examples/fixedsize.nim
    - run: nim c -d:emscripten examples/fullscreen.nim
    - run: nim c -d:emscripten examples/highdpi.nim
    - run: nim c -d:emscripten examples/httprequest.nim
    - run: nim c -d:emscripten examples/icon.nim
    - run: nim c -d:emscripten examples/opengl_version.nim
    - run: nim c -d:emscripten examples/property_changes.nim
    - run: nim c -d:emscripten examples/screens.nim
    - run: nim c -d:emscripten examples/system_cursors.nim
    - run: nim c -d:emscripten examples/tray.nim
    # - run: nim c -d:emscripten examples/websocket.nim
